### ISSUE TITLE
Any consideration for geographical features (water/mountains) that separate populations?

### ISSUE THREAD

**Issue by crwilcox** [oliviaguest/redistrict#1]
I came across http://redistrict.science/ and was looking at the map and saw something I thought may be unusual for the Seattle area. 

I live in Seattle and noticed that the districts span downtown Seattle as well as islands west of the city. While I am pointing out a specific example, I imagine many states have similar situations. Is there a consideration to perhaps consider these natural boundaries when forming districts?

![image](https://user-images.githubusercontent.com/638797/32923581-2ab2cdd6-caed-11e7-8e18-54b4708bd37e.png)

**Comment by oliviaguest** [comment]
Yes — it is possible to create such constraints by changing the input to the [weighted _k_-means](https://github.com/oliviaguest/weighted_k_means) (e.g., input super-census-block geographical units that move together as a whole). It is also possible to provide a different distance metric to take into account, e.g., elevation or travel distance. Check out the Discussion section in the preprint for more on this: https://arxiv.org/abs/1711.04640
